name: football_test
description: "Nesife: Sport Activity"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  ###
  flutter_bloc: ^8.1.6
  go_router: ^14.2.0
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  flutter_inappwebview: ^5.8.0
  http:
  url_launcher:
  firebase_core: ^2.24.2
  firebase_remote_config: ^4.3.3
  share_plus:
  dio: ^5.6.0
  cached_network_image: ^3.4.1
  ###
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/puzzle/
  fonts:
    - family: SF
      fonts:
        - asset: assets/fonts/SF-UI-Display-Regular.ttf
    - family: SFM
      fonts:
        - asset: assets/fonts/SF-UI-Display-Medium.ttf
    - family: SFB
      fonts:
        - asset: assets/fonts/SF-UI-Display-Bold.ttf